from fastapi.testclient import TestClient
import pytest
from pydantic import ValidationError
import re
import os
import sys

# Add routing_backend to path so we can import lab_api
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lab_api import IntegrationEventRequest

def test_integration_log_schema_validation():
    # Test valid payload
    valid_payload = {
        "event": "APPLIED",
        "claim_id": "SM-01",
        "applied_commit": "1234567",
        "contract_id": "LNC-AUDIT-1",
        "manifest_id": "man_1",
        "equation_fingerprint": "abc",
        "whitepaper_file": "file.md",
        "whitepaper_anchor": "header",
        "timestamp_utc": "2026-03-06T15:00:00Z"
    }
    
    # Valid
    req = IntegrationEventRequest(**valid_payload)
    assert req.event == "APPLIED"
    assert req.claim_id == "SM-01"
    
    # Invalid (missing claim_id)
    invalid_payload = valid_payload.copy()
    del invalid_payload["claim_id"]
    with pytest.raises(ValidationError):
        IntegrationEventRequest(**invalid_payload)

def test_evidence_template_regex():
    # We simulate the Evidence block generated by Svelte, and ensure it's grep-friendly
    # and has all the required keys from the 9.1 specification.
    sample_block = '''> [!NOTE] 
> **EVIDENCE:**
> - **claim_id:** SM-01
> - **contract_id:** LNC-AUDIT-12345
> - **manifest_id:** manifest_8a2b1c4
> - **claim_status:** SUPPORTED
> - **audit_status:** AUDITED
> - **equation_fingerprint:** d41d8cd98f00b204e9800998ecf8427e
> - **git_commit:** 7a92b3cf4
> - **timestamp_utc:** 2026-03-06T15:30:00Z
> - **lab_section:** Whitepapers/Claims
> - **whitepaper_target:** 06-core-ext-lineum-standard-model.md#3.1-proton-mystery'''
    
    # This proves the exact shape required to parse evidences from the raw .md strings later
    required_keys = [
        "claim_id", "contract_id", "manifest_id", "claim_status", 
        "audit_status", "equation_fingerprint", "git_commit", 
        "timestamp_utc", "lab_section", "whitepaper_target"
    ]
    
    for key in required_keys:
        # Regex to grep values out of the block easily
        pattern = rf"> \- \*\*{key}:\*\* (.*)"
        match = re.search(pattern, sample_block)
        assert match is not None, f"Key '{key}' is missing or not grep-friendly in Evidence Block"
        assert len(match.group(1).strip()) > 0
